export const guias = [
  { id: 'pagos', titulo: 'Registrar un pago y obtener el recibo', ruta: '/alumnos', permiso: 'register-payments', pasos: ['Abrí un alumno o deudor y elegí Registrar pago.', 'Revisá la deuda, elegí cómo aplicar el pago e indicá el importe y el medio recibido.', 'Guardá una vez. La confirmación permite ver o imprimir el recibo y finalizar.'], ejemplo: 'Si cobrás $30.000 de una deuda de $50.000, la aplicación automática paga primero las cuotas más antiguas.', terminos: ['Aplicación automática: distribuye el pago en las cuotas pendientes más antiguas.', 'Elegir cuotas: aplica el importe únicamente a las cuotas seleccionadas.', 'Pago a cuenta: conserva el importe como saldo a favor, sin cancelar cuotas.', 'Si falla la carga del recibo o de la lista después de guardar, reintentá esa lectura desde la confirmación. El pago ya fue registrado.'] },
  { id: 'cierre', titulo: 'Cerrar la caja del día', ruta: '/caja', permiso: 'operate-cash', pasos: ['Contá el efectivo físico e ingresá el total contado.', 'Indicá cuánto dejás para la próxima apertura. Revisá el efectivo a retirar y la diferencia.', 'Revisá los datos y confirmá el cierre.'], ejemplo: 'Contado $100.000 y saldo para apertura $20.000: el efectivo retirado será $80.000.', terminos: ['Total esperado: efectivo que debería haber según los movimientos registrados.', 'Diferencia: total contado menos total esperado; se registra al cerrar.', 'Saldo para próxima apertura: efectivo que queda disponible para la próxima caja de la sucursal.'] },
  { id: 'reportes', titulo: 'Consultar reportes y guardar favoritas', ruta: '/reportes', pasos: ['Elegí la sección y el período. Hoy y Este mes consultan directamente.', 'Para fechas o filtros manuales, pulsá Aplicar. Las etiquetas describen la consulta cargada; los cambios pendientes se indican aparte.', 'Guardá la consulta actual como favorita para reutilizarla desde cualquier equipo.'], ejemplo: 'Este mes abarca desde el primer día del mes hasta hoy. Una favorita con ese período recalcula las fechas cada vez que la aplicás.', terminos: ['Quitar una etiqueta vuelve a consultar sin ese filtro.', 'Limpiar filtros consulta sin período ni filtros adicionales, dentro de tus permisos.', 'Una favorita conserva tus filtros, no concede permisos. Si la sucursal o el cajero ya no están disponibles, actualizala con filtros autorizados.', 'El historial de cajas permite a Administración, Tesorería y Superadmin consultar cajeros de las sucursales autorizadas. Caja consulta sus propias cajas; Consulta accede al resumen agregado.'] },
]

export const novedades = [
  { fecha: '2026-09-30', titulo: 'Consultas más claras y confirmación de pagos', descripcion: 'Reportes incorpora Hoy, Este mes, etiquetas de filtros y consultas favoritas guardadas en la cuenta. Caja permite reutilizar sus filtros de movimientos.', enlaces: [{ ruta: '/reportes', texto: 'Consultar reportes' }, { ruta: '/caja', texto: 'Consultar Caja' }] },
  { fecha: '2026-09-30', titulo: 'Detalle de operaciones y recibos', descripcion: 'Los pagos y movimientos tienen un panel de detalle. Después de registrar un pago, la confirmación permanece abierta para consultar o imprimir el recibo. Si falla una lectura posterior, se puede reintentar desde la confirmación.', enlaces: [{ ruta: '/alumnos', texto: 'Directorio de alumnos' }, { ruta: '/deudores', texto: 'Cartera de deudores' }] },
  { fecha: '2026-09-30', titulo: 'Ayuda a demanda', descripcion: 'Guías breves para registrar pagos, cerrar cajas y consultar reportes, disponibles según las acciones permitidas por tu perfil.', enlaces: [{ ruta: '/ayuda', texto: 'Abrir ayuda' }] },
]
