# Generated by Django 6.0.7 on 2026-07-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cajadiaria_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='activa', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.carreracurso')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.conceptocobrable')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.sucursal')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.matricula')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='core.pago')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='core.cuota')),
            ],
            options={
                'ordering': ['creado', 'id'],
                'unique_together': {('pago', 'cuota')},
            },
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('alumno', 'carrera'), name='unique_active_enrollment_per_course'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('alumno', 'concepto', 'periodo'), name='unique_student_fee_period'),
        ),
    ]
