# Generated by Django 6.0.7 on 2026-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_matricula_cuota_aplicacionpago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
