# Generated by Django 6.0.7 on 2026-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_payment_receipt_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('administracion', 'Administracion'), ('tesoreria', 'Tesoreria'), ('caja', 'Caja'), ('consulta', 'Consulta')], default='consulta', max_length=30),
        ),
    ]
