# Generated by Django 6.0.7 on 2026-08-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pago_saldo_pendiente_posterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='importe_retirado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='saldo_arrastrable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='medio',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=30),
        ),
        migrations.CreateModel(
            name='SaldoArrastrableCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utilizado_en', models.DateTimeField(blank=True, null=True)),
                ('caja_destino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saldo_recibido', to='core.cajadiaria')),
                ('caja_origen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_generado', to='core.cajadiaria')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_caja', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'saldo arrastrable de caja',
                'verbose_name_plural': 'saldos arrastrables de caja',
                'ordering': ['-caja_origen__fecha', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('caja_destino__isnull', True)), fields=('sucursal',), name='unique_pending_cash_balance_per_branch')],
            },
        ),
    ]
