# Generated by Django 6.0.7 on 2026-08-20 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cajadiaria_importe_retirado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionpago',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aplicacionpago',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='movimiento_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_reverso', to='core.movimientocaja'),
        ),
        migrations.AddField(
            model_name='pago',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='anulado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('anulado', 'Anulado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('pago', 'Pago'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('retiro', 'Retiro'), ('pase', 'Pase'), ('reverso', 'Reverso de pago')], max_length=30),
        ),
    ]
