# Generated by Django 6.0.7 on 2026-08-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eventoauditoria'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='unique_active_enrollment_per_course',
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('alumno',), name='unique_active_enrollment_per_student'),
        ),
    ]
