# Generated by Django 6.0.7 on 2026-08-20 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_matricula_unique_active_enrollment_per_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='descuento_registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_cuota', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuota',
            name='motivo_descuento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuota',
            name='recargo_calculado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReglaRecargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('importe', 'Importe fijo'), ('porcentaje', 'Porcentaje')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_tolerancia', models.PositiveIntegerField(default=0)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_recargo', to='core.conceptocobrable')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_recargo', to='core.sucursal')),
            ],
            options={
                'ordering': ['sucursal', 'concepto', 'dias_tolerancia', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='regla_recargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.reglarecargo'),
        ),
        migrations.CreateModel(
            name='TipoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('importe', 'Importe fijo'), ('porcentaje', 'Porcentaje')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_descuento', to='core.sucursal')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'sucursal')},
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='tipo_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='core.tipodescuento'),
        ),
    ]
