# Generated by Django 6.0.7 on 2026-09-30 22:42

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfilusuario_debe_cambiar_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('pantalla', models.CharField(max_length=16)),
                ('configuracion', models.JSONField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('propietario'), models.F('pantalla'), name='favorita_nombre_cuenta_pantalla'), models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='favorita_nombre_no_vacio'), models.CheckConstraint(condition=models.Q(('pantalla__in', ['caja', 'reportes'])), name='favorita_pantalla_valida')],
            },
        ),
    ]
