# Generated by Django 6.0.7 on 2026-10-07 19:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cuota_desglose_movimiento_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('porcentaje_mensual', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('base_calculo', models.CharField(choices=[('dia_1_del_mes', 'Desde el día 1 del mes del período'), ('fecha_vencimiento', 'Desde la fecha de vencimiento')], default='dia_1_del_mes', max_length=30)),
                ('unidad_calculo', models.CharField(choices=[('meses', 'Meses completos'), ('dias', 'Días prorrateados (30 por mes)')], default='meses', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=160)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_interes', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'tasa de interés',
                'verbose_name_plural': 'tasas de interés',
                'ordering': ['-vigencia_desde', 'id'],
            },
        ),
    ]
